import Head from 'next/head'
import Image from 'next/image'

import dynamic from 'next/dynamic'
import { Suspense, useEffect, useState } from 'react'
//Images
import mainimage from '../public/main.png'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/router'

export default function Home() {
  const {data:session} = useSession()
  let router = useRouter()
  const[router1, setRouter] = useState(router)

  useEffect(()=>{
    if(session) {
      router.push("/browse")
    }
  }, [])

  const Navbar = dynamic(() => import("../components/Navbar").then(res=>res.default), {
    suspense: true
  })

  const Landing = dynamic(() => import("../components/Landing").then(res=>res.default), {
    suspense: true
  })

  const Section1 = dynamic(()=>import("../components/Section1").then(res=>res.default), {
    suspense: true
  })

  const Section2 = dynamic(()=>import("../components/Section2").then(res=>res.default), {
    suspense: true
  })

  const FAQ = dynamic(()=>import("../components/FAQ").then(res=>res.default), {
    suspense: true
  })

  return (
    <>
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/netflix.ico" />
      </Head>
      <div className='bg-black'>
        <div className=''>
          <Image className='absolute w-[100%] object-cover brightness-50 h-[700px]' src={mainimage} alt="Main_image"></Image>
            <Suspense fallback={<div>Loading...</div>}>
              <Navbar />
              <Landing /> 
              <div className='h-[175px]'></div>
              <Section1 />
              <Section2 />
              <FAQ /> 
            </Suspense>
        </div>
      </div>
    </>
  )
}
